USE [master]
GO

/****** Object:  Database [TodoDB]    Script Date: 07.04.2023 20:00:51 ******/
CREATE DATABASE [TodoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TodoDB', FILENAME = N'D:\Study\ДУ «Житомирська політехніка»\II курс\I семестр\Бази даних\TodoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TodoDB_log', FILENAME = N'D:\Study\ДУ «Житомирська політехніка»\II курс\I семестр\Бази даних\TodoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TodoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TodoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TodoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TodoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TodoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TodoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TodoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TodoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TodoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TodoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TodoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TodoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TodoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TodoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TodoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TodoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TodoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TodoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TodoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TodoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TodoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TodoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TodoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TodoDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TodoDB] SET  MULTI_USER 
GO

ALTER DATABASE [TodoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TodoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TodoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TodoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TodoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TodoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TodoDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TodoDB] SET  READ_WRITE 
GO

